import { build } from "bun";
import { exit } from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN
if you want to view the source, please visit the github repository of this plugin
*/
`;

const result = await build({
	entrypoints: ["src/main.ts"],
	outdir: ".",
	naming: "[name].js",
	format: "cjs",
	target: "node",
	banner: banner,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	sourcemap: "none",
	minify: true,
});

if (!result.success) {
	console.error("Build failed:", result.logs);
	exit(1);
}

if (!result.outputs || result.outputs.length === 0) {
	console.error("No output generated!");
	exit(1);
}

console.debug("Build complete! Output written to main.js");
