import { build } from "bun";
import { watch } from "fs";
import { exit } from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY BUN
if you want to view the source, please visit the github repository of this plugin
*/
`;

const externalPackages = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
];

async function doBuild() {
	const result = await build({
		entrypoints: ["src/main.ts"],
		outdir: ".",
		naming: "[name].js",
		format: "cjs",
		target: "node",
		banner: banner,
		external: externalPackages,
		sourcemap: "inline",
		minify: false,
	});

	if (!result.success) {
		console.error("Build failed:", result.logs);
		return;
	}

	if (result.outputs && result.outputs.length > 0) {
		console.debug("Rebuilt main.js");
	}
}

// Initial build
await doBuild();
console.debug("Watching for changes...");

// Watch mode using fs.watch
const watcher = watch("src", { recursive: true }, async (eventType, filename) => {
	if (filename && (filename.endsWith(".ts") || filename.endsWith(".tsx"))) {
		await doBuild();
	}
});

// Keep the process alive
process.on("SIGINT", () => {
	watcher.close();
	exit(0);
});
